# Generated by Django 4.2.7 on 2024-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zork', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesion', models.CharField(max_length=250)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='quesion',
        ),
        migrations.AddField(
            model_name='room',
            name='quesion',
            field=models.ManyToManyField(to='zork.quesion'),
        ),
    ]
