# Generated by Django 4.2.7 on 2024-06-09 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zork', '0002_quesion_remove_room_quesion_room_quesion'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='atherrooms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zork.room'),
        ),
    ]
