# Generated by Django 4.2.7 on 2024-06-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zork', '0003_room_atherrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='quesion',
            name='answer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
