# Generated by Django 5.0.3 on 2024-07-07 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zork', '0004_quesion_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
    ]
